name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '26 6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl 'https://www.ssb.no/en/inntekt-og-forbruk/forbruk/statistikk/forbruksundersokelsen' | sed 's/<script>.*<\/script>//g;/<script>/,/<\/script>/{/<script>/!{/<\/script>/!d}};s/<script>.*//g;s/.*<\/script>//g;s/<!-- Google Tag Manager -->.*<!-- MAIN -->//g' > forbruksundersokelsen-2023.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
